version:2.1

Jobs:
  client_testing:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version:"20.10.11"
      - run:
          command: docker build -t jay/client-test -f ./client-typescript/D
          name: building the client for testing
      - run:
          command: docker run jay/client-test npm test
          name: run the client tests

workflows:
  version:2
  testing:
    jobs: